### ISSUE TITLE
How I can contact with You? 

### ISSUE THREAD

**Issue by kubaceg** [magento-hackathon/Shipping-rates-grid-in-Magento#2]
Hey guys! I want contribute in this extension, how can I contact with you?

**Comment by daim2k5** [comment]
Fork the Project and make PR

**Comment by kubaceg** [comment]
Yeach but I don't know what is done, what is todo and who make what at this moment ;)

**Comment by daim2k5** [comment]
Right, so please project team write some issues for @kubaceg
